apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: madara-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: chiraag77/madara_speech


---

apiVersion: v1
kind: Service
metadata:
  name: madara-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

